version: 2.1
orbs:
  fast: wallarm/fast@dev:0.1.18
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout

      - run:
          name: Build docker
          command: |
            docker build -t app-test .

      - run:
          name: Run application
          command: |
            docker run -d --name app-test -p 3000:3000 app-test

      - fast/run_security_tests:
          app_port: "3000"
          test_record_id: "3612" # use your test_record_id
          policy_id: "129" # use your policy_id
          wallarm_api_host: api.wallarm.com
