version: 2.1
orbs:
  fast: wallarm/fast@dev:0.1.18
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout

      - fast/run_security_tests:
          app_uri: "google-gruyere.appspot.com"
          app_protocol: "http"
#          get_internal_ip: "hostname -i | grep -o -E '([0-9]{1,3}[\.]){3}[0-9]{1,3}' | head -n1"
          test_run_name: "test1"
          test_run_desc: "test1"
          test_run_rps: "1"
          stop_on_first_fail: "False"
          wallarm_fast_port: "9999"
          app_port: "3000"
          test_record_id: "2690" # use your test_record_id
          policy_id: "129" # use your policy_id
          wallarm_api_host: api.wallarm.com
