version: 2.1
orbs:
  fast: wallarm/fast@dev:0.1.19
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout

      - fast/run_security_tests:
          app_host: "http://google-gruyere.appspot.com:80"
          app_port: "80"
          test_run_name: "test1"
          test_run_desc: "test1"
          test_run_rps: "1"
          stop_on_first_fail: False
          wallarm_fast_port: "9999"
          test_record_id: "2690" # use your test_record_id
          policy_id: "129" # use your policy_idd
          wallarm_api_host: api.wallarm.com
